import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Theme } from "@radix-ui/themes"
import { SideMenu } from "./_components"
import styles from "./layout.module.css"

import "./globals.css"
import "@radix-ui/themes/styles.css"
import { className } from "./utils"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <div className={styles.root}>
            <SideMenu />
            <div>{children}</div>
          </div>
        </Theme>
      </body>
    </html>
  )
}
